### ISSUE TITLE
Document DNS requirements for Workers

### ISSUE THREAD

**Issue by rita3ko** [cloudflare/workers-docs-engine#160]
If a user has a zone already on Cloudflare, it is easy for us to allow them to set up a custom hostname. 
It will take some work for us to actually allow people to CNAME to their zoneless Workers, but in the meantime, developers can still deploy to their own custom sites. 

To support this without requiring too much user involvement, we would need to:

- Create a dummy DNS record (if one doesn't already exist for the hostname), i.e. to 1.2.3.4 (to allow external DNS to resolve)
- Create a wildcard route for the hostname (somewhat related: https://github.com/cloudflare/wrangler/issues/76 ). 

We should document this as the recommended path for custom hostnames (will create separate issue in docs).

**Comment by adamschwartz** [comment]
@ispivey @rita3ko Please correct me if I’m wrong, but I believe this may cover it:

https://github.com/cloudflare/workers-docs-engine/blob/4b8501576d3ff65a9d981ba8c06b4afee648c060/src/content/learning/getting-started.md#L349

![image](https://user-images.githubusercontent.com/154613/90659318-88c32300-e212-11ea-9a88-2d3553534a1a.png)

**Comment by ispivey** [comment]
Yes, absolutely, this is what the issue was about. I'll PR a small tweak, now that I'm thinking about it: we should recommend an AAAA record to `100::`, which is the reserved IPv6 discard prefix, which ensures requests to "origin" will be immediately discarded/timed out.

**Comment by adamschwartz** [comment]
Good to know. I need to update my site now... hehe.

**Comment by ispivey** [comment]
Hehe... it's not super important, but it's definitely the safest and most foolproof way to do accomplish this, so figure we should recommend it explicitly.
