### ISSUE TITLE
Use 404 page for all 404s

### ISSUE THREAD

**Issue by adamschwartz** [cloudflare/workers-docs-engine#166]
We have a 404 page, which can be viewed here:
https://developers.cloudflare.com/workers/404

But for some reason, it’s not being served on any other 404 page, e.g.:
https://developers.cloudflare.com/workers/this-page-does-not-exist

**Comment by EverlastingBugstopper** [comment]
if this is workers sites - need to make sure that DEBUG is not set to true in the source code when pushed to prod. could set up with wrangler environment variables

**Comment by ispivey** [comment]
I don't think `DEBUG` is set to `true`. I checked three places:
* https://github.com/cloudflare/workers-docs-engine/blob/master/workers-site/index.js#L11
* https://github.com/cloudflare/workers-docs-engine/blob/master/.github/workflows/deploy.yml
* https://github.com/cloudflare/workers-docs-engine/blob/master/wrangler.toml

It's explicitly set to `false` and I don't see it being overridden anywhere.

However, it looks like we will fail to serve the 404 page, and show this error, if looking up the 404 page fails: https://github.com/cloudflare/workers-docs-engine/blob/master/workers-site/index.js#L54-L61

Is the problem perhaps that we're looking up `https://developers.cloudflare.com/404.html` in our asset manifest and failing to find it, when we should be looking up `https://developers.cloudflare.com/workers/404.html` instead?

I'll test a quick tweak.

**Comment by ispivey** [comment]
Whoo, that worked!

**Comment by adamschwartz** [comment]
You rock.
