### ISSUE TITLE
Missing VCL examples

### ISSUE THREAD

**Issue by vences** [cloudflare/workers-docs-engine#171]
Hi,

In the previous docs there was an archive section with VCL examples. 
Here the previous link: https://developers.cloudflare.com/workers/archive/recipes/vcl-conversion/

Is there any plan to move it to the brand new example section?
Thks,

**Comment by adamschwartz** [comment]
Content files:

https://github.com/cloudflare/workers-docs/tree/master/workers-docs/src/content/archive/recipes/vcl-conversion

@rita3ko @davidtsong Should we add these?

**Comment by rita3ko** [comment]
@vences — many of these are now examples in some form. We had the VCL conversion docs in there originally when Workers started out primarily as a way to help control the CDN. As we've evolved to a serverless platform model, I don't think it makes as much sense to present that content in the same way.

**Comment by vences** [comment]
Thks @rita3ko! Understood, some implementations  are still using Workers to control CDN but in that case I suppose I can go to the older github repo and/or I need to look at more closely the examples :)
Thanks,
