### ISSUE TITLE
`postbuild` script needs configurable `pathPrefix` (or equivalent)

### ISSUE THREAD

**Issue by adamschwartz** [cloudflare/workers-docs-engine#217]
As part of prepping #66, we’ve made `pathPrefix` a configurable option in `docs-config.js`, e.g.:

https://github.com/cloudflare/workers-docs-engine/blob/28b9fe4f93cb76263571a452c4e74f1ffd70546e/docs-config.js#L3

While this property is now consumed by the docs engine in a number of places, one place that a hard-coded `workers` still remains is inside `bin/postbuild`:

https://github.com/cloudflare/workers-docs-engine/blob/28b9fe4f93cb76263571a452c4e74f1ffd70546e/bin/postbuild#L5

As a result, in order to make https://github.com/adamschwartz/docs-engine-example work, we needed to set `pathPrefix` to `""` and then hard-code the Workers Sites bucket to include the `/workers` suffix:

```toml
[site]
bucket = ".docsengine/docs-engine/public/workers" # TODO: support non-`/workers` pathPrefix
```

https://github.com/adamschwartz/docs-engine-example/blob/c3bedf1f2211a9e5fde795e1c3e192e280e69afb/wrangler.toml#L7

In order to make this work, we’ll minimally need to allow `postbuild` to pass in a variable, e.g. something like:

```bash
bin/postbuild --pathPrefix="/workers"
```

Ideally, we wouldn’t even need to do this. Instead `bin/postbuild` could e.g. be rewritten in Node and `require("./docs-config.js")` just as `gatsby-config.js` does.

cc @signalnerve @ispivey

**Comment by signalnerve** [comment]
ok to do this via an env var? probably easier to build into the script than argument/flag parsing

**Comment by adamschwartz** [comment]
This is now solved with the new `node postbuild.js` command:

Run here:
https://github.com/adamschwartz/cloudflare-docs-engine/blob/33bd3fafe6b5b97006c2654edb255e85ebdafb02/bin/commands.sh#L94

Pulls in config here:
https://github.com/adamschwartz/cloudflare-docs-engine/blob/33bd3fafe6b5b97006c2654edb255e85ebdafb02/bin/postbuild.js#L3
