### ISSUE TITLE
Need proper utf-8 encoding

### ISSUE THREAD

**Issue by adamschwartz** [cloudflare/workers-docs-engine#218]
On Twitter page titles show up like this:

<img width="486" src="https://user-images.githubusercontent.com/154613/91506250-ac840a00-e89f-11ea-988e-1bb163dc0cfb.png"/>

--------

Full view

![image](https://user-images.githubusercontent.com/154613/91506224-9e35ee00-e89f-11ea-9f98-4f7020313f05.png)

--------

This I believe is due to a bug in https://github.com/cloudflare/kv-asset-handler which [was fixed](https://github.com/cloudflare/kv-asset-handler/pull/130/commits/78037a17864a681971439639f1f2d7d85b8908f9) with [`78037a1` (#130)](https://github.com/cloudflare/kv-asset-handler/pull/130/commits/78037a17864a681971439639f1f2d7d85b8908f9).

However I believe a new version of `kv-asset-handler` would need to be cut in order for us to consume the fix. Currently [we’re on `v0.0.11`](https://github.com/cloudflare/workers-docs-engine/blob/28b9fe4f93cb76263571a452c4e74f1ffd70546e/workers-site/package-lock.json#L8) which was released on June 30, whereas the fix was on Jul 2.

@EverlastingBugstopper can you please cut a new release of `kv-asset-handler`?

cc @ispivey @rita3ko @davidtsong

**Comment by EverlastingBugstopper** [comment]
Haha hey I don't work here anymore! No permissions, sorry 😁

**Comment by adamschwartz** [comment]
Still unfortunately waiting on https://github.com/cloudflare/kv-asset-handler to release a new version.

**Comment by ispivey** [comment]
@adamschwartz https://github.com/cloudflare/kv-asset-handler/releases/tag/v0.0.12 should have what you're looking for

**Comment by adamschwartz** [comment]
Thanks everybody. This is fixed as of https://github.com/cloudflare/workers-docs-engine/commit/df2e04dc59048bcea73eb4917bb772afc9ee25ce.

![image](https://user-images.githubusercontent.com/154613/92308043-c5a84d00-ef68-11ea-9fb4-14ad83487497.png)
