### ISSUE TITLE
Localize a website hero image links to "unsafe" page

### ISSUE THREAD

**Issue by adamschwartz** [cloudflare/workers-docs-engine#223]
On https://developers.cloudflare.com/workers/tutorials/localize-a-website, clicking the first image here:

![image](https://user-images.githubusercontent.com/154613/91784796-c429fe00-ebd1-11ea-9760-09b4d3b7093c.png)

Takes you to https://i18n-example.workers-tooling.cf/ which shows this:

![image](https://user-images.githubusercontent.com/154613/91784832-d4da7400-ebd1-11ea-8954-2217564d15aa.png)

**Comment by bulk88** [comment]
This is still a problem, workers-tooling.cf domain is hosting malware now by a clickjacker.
