### ISSUE TITLE
Can't select shell commands

### ISSUE THREAD

**Issue by greg-mckeon** [cloudflare/workers-docs-engine#273]
When I try to highlight a shell command to select it, I cannot highlight the first part of the command.

See any of the commands here: https://developers.cloudflare.com/workers/learning/using-durable-objects#defining-a-durable-object-namespace

**Comment by koeninger** [comment]
have you tried just using "```" rather than "```sh" ?

**Comment by greg-mckeon** [comment]
Yeah, it's because of the code-unselectable regex.  I'll create a pr without sh as the language.
