### ISSUE TITLE
Handle redirects for new docs content

### ISSUE THREAD

**Issue by signalnerve** [cloudflare/workers-docs-engine#41]
most if not all of the tutorials are getting new names/URLs during the redesign, we need to handle redirecting from the old URLs here: https://github.com/cloudflare/workers-docs/blob/master/workers-docs/workers-site/redirects/newDocs.js

**Comment by adamschwartz** [comment]
Agreed. This will be a problem with pages in general. About content will b in Learning, Examples and Tutorials sections will have diff URLs, etc. Maybe we should just make this issue about handling redirects in general?

**Comment by adamschwartz** [comment]
Plan is to use https://github.com/signalnerve/lilredirector

**Comment by signalnerve** [comment]
yay, lilredirector!

@adamschwartz can you create a new kv namespace called `REDIRECTS` and put the binding/id in wrangler.toml? i can carry it the rest of the way. see docs for instructions: https://github.com/signalnerve/lilredirector#installation

**Comment by adamschwartz** [comment]
All set https://github.com/cloudflare/workers-docs-engine/commit/f643536937d98a4158d61cf873326f57ccd589f0
