### ISSUE TITLE
Fix search API/results

### ISSUE THREAD

**Issue by adamschwartz** [cloudflare/workers-docs-engine#61]
The Algolia results currently are coming from the old (current) site:

![image](https://user-images.githubusercontent.com/154613/88105798-7e116180-cb72-11ea-9b0a-fb2512804482.png)

We’ll need to either create a new Algolia account or have it re-crawl once we launch. The crawl probably takes some time / has a delay, so we need to be thoughtful about the coordination of this.

**Comment by ispivey** [comment]
@rita3ko @adamschwartz @signalnerve do any of you have access to log in to our Algolia account? If not, any suggestions on who I should bother to get such access? I bet there's a way to create a new (separate) index and get it all warmed up, without creating a brand new account.

**Comment by rita3ko** [comment]
i honestly have no idea. maybe dane knows?

**Comment by adamschwartz** [comment]
@signalnerve Mentioned today that we’ve made PRs against Algolia’s docsearch config repo https://github.com/algolia/docsearch-configs/pull/1071 in the past.

**Comment by signalnerve** [comment]
indeed! the docs stuff for algolia, at least back in 2019, was managed via that repo. we should just be able to create a new config there (or maybe update that one, since the URLs will generally not change). there are a few specific config things in there around CSS selectors for targeting h1/h2/h3 etc that @adamschwartz should sign off on. @ispivey i think you should be ok to send a PR to that repo and then tag adam and i in for review!

https://github.com/algolia/docsearch-configs/blob/master/configs/workers-cloudflare.json

**Comment by adamschwartz** [comment]
From `algolia/docsearch-configs@master/configs/workers-cloudflare.json` at that link, the selectors are currently:

```json
"selectors": {
  "lvl0": "#body-inner h1",
  "lvl1": "#body-inner h2",
  "lvl2": "#body-inner h3",
  "lvl3": "#body-inner h4",
  "lvl4": "#body-inner h5",
  "lvl5": "#body-inner h6",
  "text": "#body-inner p, #body-inner li"
}
```

I would just change all of the instances of `#body-inner` to `.DocsContent`, and we should be good to go.

`#body-inner p, #body-inner li` strikes me as a little odd, but that seems to have been working fine so I’m happy to try `.DocsContent p, .DocsContent li` for now and see how well it indexes.

**Comment by adamschwartz** [comment]
For the sitemap: https://www.gatsbyjs.org/packages/gatsby-plugin-sitemap (from @signalnerve).

**Comment by adamschwartz** [comment]
Sitemap PR https://github.com/cloudflare/workers-docs-engine/pull/99

**Comment by adamschwartz** [comment]
Fixed with https://github.com/cloudflare/workers-docs-engine/commit/bb62e2af0633030a587ef4be2d4b9fc184dc3575 (and https://github.com/cloudflare/workers-docs-engine/commit/0fd7a283d0afe7f5eef8015b79044529b4eeef8d).
