### ISSUE TITLE
Build is broken after merging v0

### ISSUE THREAD

**Issue by adamschwartz** [cloudflare/workers-docs-engine#63]
After [merging the `v0` branch](https://github.com/cloudflare/workers-docs-engine/pull/62), which added a few dozen pages, the build is now breaking due to the `app.js` build exceeding KV’s limit:

![image](https://user-images.githubusercontent.com/154613/88261703-c9bc2c00-cc94-11ea-828e-93a251d451c8.png)

@ispivey @rita3ko what should we do?

**Comment by ispivey** [comment]
In October 2019, the maximum size was increased to 10MB with https://github.com/cloudflare/wrangler/pull/806 , which appears to have been released in wrangler 1.5.0.

I think we just need to update the version of the Action we're using for deployment.
