### ISSUE TITLE
Add missing Storage content

### ISSUE THREAD

**Issue by ispivey** [cloudflare/workers-docs-engine#72]
There are a number of links to https://developers.cloudflare.com/workers/reference/storage , which doesn't exist here. We should figure out what needs to be migrated and migrate it.

**Comment by adamschwartz** [comment]
For now, how would you feel about changing the links to https://workers-docs.ruthless.design/reference/runtime-apis/kv ?

**Comment by davidtsong** [comment]
^^ that page looks pretty good - I think I can just move the bottom section "see more" up to the top and then it'd be practically the same

**Comment by adamschwartz** [comment]
@ispivey @davidtsong can this be closed?

**Comment by davidtsong** [comment]
Yeah I think this can be closed. I added in a new issue to expand more of this content anyways https://github.com/cloudflare/workers-docs-engine/issues/213
