### ISSUE TITLE
Improve `addEventListener` reference doc

### ISSUE THREAD

**Issue by ispivey** [cloudflare/workers-docs-engine#73]
Migrate https://developers.cloudflare.com/workers/reference/apis/addEventListener/ here.

**Comment by davidtsong** [comment]
Should this be a standalone page or can we add this to the FetchEvent page for now?

**Comment by adamschwartz** [comment]
My vote would be to migrate it as a separate page. Easier for people to discover in the sidebar.

**Comment by davidtsong** [comment]
https://github.com/cloudflare/workers-docs-engine/pull/76

**Comment by adamschwartz** [comment]
I merged https://github.com/cloudflare/workers-docs-engine/pull/76 for now, but let’s see if we can still find some time to improve this page for MVP.

**Comment by adamschwartz** [comment]
Good enough for now:

![image](https://user-images.githubusercontent.com/154613/89076611-a2c5c000-d34e-11ea-8e76-fe3fe4451134.png)
