### ISSUE TITLE
[QA] make sure links work

### ISSUE THREAD

**Issue by adamschwartz** [cloudflare/workers-docs-engine#83]

**Comment by davidtsong** [comment]
I think I got this working now...
- the plugin thinks these are broken links(but they got the # format for Mdx)
`
124 broken links found

warn 2 broken links found on /tutorials/localize-a-website
warn 103:4    #understanding-data-i18n-key
warn 253:241  /learning/getting-started#6a-obtaining-your-account-id-and-zone-id
⠀
warn 4 broken links found on /tutorials/deploy-a-static-wordpress-site
warn  57:5    /platform/sites/config
warn  99:259  /learning/getting-started#6a-obtaining-your-account-id-and-zone-id
warn 103:149  /learning/getting-started#6-configure-your-project-for-deployment
warn 119:161  /learning/getting-started#optional-configure-for-deploying-to-a-registered-domain
⠀
warn 1 broken links found on /tutorials/deploy-a-react-app-with-create-react-app
warn  61:168  /learning/getting-started#6d-configuring-your-project
⠀
warn 1 broken links found on /tutorials/build-a-slackbot
warn 627:323  /cli-wrangler/commands#secret
⠀
warn 4 broken links found on /tutorials/authorize-users-with-auth0
warn 104:195  /cli-wrangler/commands#secret
warn 806:86   /learning/getting-started#optional-configure-for-deploying-to-a-registered-domain
warn 806:421  /learning/getting-started#optional-configure-for-deploying-to-a-registered-domain
warn 838:126  /learning/getting-started#6d-configuring-your-project
⠀
warn 1 broken links found on /runtime-apis/add-event-listener
warn  20:65   /runtime-apis/fetch-event#methods
⠀
warn 1 broken links found on /runtime-apis/fetch
warn  13:156  /runtime-apis/fetch-event#methods
⠀
warn 9 broken links found on /runtime-apis/kv
warn  36:14   /cli-wrangler/commands#kvkey
warn  45:9    /cli-wrangler/commands#kvbulk
warn  80:14   /cli-wrangler/commands#kvkey
warn 119:14   /cli-wrangler/commands#kvkey
warn 159:14   /cli-wrangler/commands#kvkey
warn 177:14   /cli-wrangler/commands#kvkey
warn 205:135  #pagination
warn 245:3    /platform/limits#kv-limits
warn 246:3    /platform/pricing#kv
⠀
warn 4 broken links found on /runtime-apis/request
warn  41:78   #requestinit
warn  41:112  #requestinitcfproperties
warn 153:184  #constructor
warn 301:10   /reference/apis/fetch-event/
⠀
warn 5 broken links found on /runtime-apis/response
warn  42:71   /runtime-apis/request#parameters
warn  95:13   #response
warn  99:13   #response
warn 103:13   #response
warn 107:13   #response
⠀
warn 1 broken links found on /runtime-apis/web-crypto
warn   9:83   #supported-algorithms
⠀
warn 3 broken links found on /runtime-apis/web-standards
warn  66:47   /runtime-apis/request#the-request-context
warn  83:53   /runtime-apis/request#the-request-context
warn 105:154  /cli-wrangler/webpack/#shimming-globals
⠀
warn 2 broken links found on /platform/environments
warn  22:271  /cli-wrangler/configuration#keys
warn 262:140  /cli-wrangler/commands#secret
⠀
warn 19 broken links found on /platform/limits
warn  14:3    #request
warn  15:3    #memory
warn  16:3    #cpu-runtime
warn  17:3    #subrequests
warn  18:3    #simultaneous-open-connections
warn  19:3    #environment-variables
warn  20:3    #environment-variables
warn  21:3    #script-size
warn  22:3    #number-of-scripts
warn  32:3    #kv
warn  33:3    #kv
warn  34:3    #kv
warn  35:3    #kv
warn  36:3    #kv
warn  37:3    #kv
warn  47:3    #cache-api
warn  48:3    #cache-api
warn  49:3    #cache-api
warn 139:27   /platform/scripts#resource-bindings
⠀
warn 2 broken links found on /platform/routes
warn  25:18   #matching-behavior
warn  27:64   /platform/limits#request-limits
⠀
warn 1 broken links found on /platform/scripts
warn  59:23   /learning/how-kv-works
⠀
warn 6 broken links found on /platform/sites/start-from-existing
warn   6:99   /cli-wrangler/install-update#update
warn  14:59   /tutorials/hosting-static-wordpress-sites
warn  41:228  /learning/getting-started#6a-obtaining-your-account-id-and-zone-id
warn  49:53   /learning/getting-started#configure-for-deploying-to-workersdev
warn  49:152  /learning/getting-started#optional-configure-for-deploying-to-a-registered-domain
warn  62:20   /learning/getting-started#6-configure-your-project-for-deployment
⠀
warn 5 broken links found on /platform/sites/start-from-scratch
warn   8:42   /cli-wrangler/install-update#update
warn  22:225  /learning/getting-started#6a-obtaining-your-account-id-and-zone-id
warn  30:53   /learning/getting-started#configure-for-deploying-to-workersdev
warn  30:152  /learning/getting-started#optional-configure-for-deploying-to-a-registered-domain
warn  49:20   /learning/getting-started#6-configure-your-project-for-deployment
⠀
warn 1 broken links found on /platform/sites/start-from-worker
warn   6:99   /cli-wrangler/install-update#update
⠀
warn 3 broken links found on /learning/debugging-workers
warn  56:67   /cli-wrangler/commands#dev-alpha
warn  95:68   /cli-wrangler/commands#tail
warn 112:42   /platform/limits#daily-request
⠀
warn 15 broken links found on /learning/getting-started
warn  22:22   /cli-wrangler/commands#publish
warn  32:66   /cli-wrangler/commands#generate
warn  32:111  /cli-wrangler/commands#configure
warn  32:158  /cli-wrangler/commands#build
warn  32:197  /cli-wrangler/commands#preview
warn  32:244  /cli-wrangler/commands#publish
warn  51:12   /cli-wrangler/commands#generate
warn  51:149  /cli-wrangler/commands#generate
warn  82:65   /cli-wrangler/commands#init
warn  97:228  /learning/how-workers-works#isolates
warn 118:16   /runtime-apis/fetch-event#methods
warn 122:45   /runtime-apis/fetch-event#methods
warn 160:15   /runtime-apis/request#properties
warn 162:95   /runtime-apis/request#incomingrequestcfproperties
warn 382:53   /cli-wrangler/configuration#environments
⠀
warn 1 broken links found on /learning/how-the-cache-works
warn  64:103  /platform/limits#cache-api-limits
⠀
warn 1 broken links found on /learning/using-streams
warn  23:134  /runtime-apis/streams/readablestream#methods
⠀
warn 4 broken links found on /learning/workers-metrics
warn  31:395  /learning/debugging-workers#error-pages-generated-by-workers
warn  45:71   /platform/limits#request-limits
warn  49:48   /cli-wrangler/commands#tail
warn  53:339  /platform/limits#cpu-runtime
⠀
warn 1 broken links found on /docs-engine/code-block-examples
warn  14:18   /docs-engine/docs-flavored-markdown#codeblocks
⠀
warn 5 broken links found on /docs-engine/docs-flavored-markdown
warn 391:34   #highlight
warn 391:67   #filenames
warn 478:27   #filenames
warn 553:72   #type
warn 553:112  #frontmatter
⠀
warn 7 broken links found on /docs-engine/example-pages/class
warn  10:3    #
warn  11:3    #
warn  12:3    #
warn  54:139  #learning-page-about-debugging
warn  60:3    #
warn  61:3    #
warn  63:3    #
⠀
warn 4 broken links found on /cli-wrangler/commands
warn 147:161  #subdomain
warn 219:62   /cli-wrangler/configuration#dev
warn 238:18   /cli-wrangler/configuration#kv_namespaces
warn 299:18   /cli-wrangler/configuration#kv_namespaces
⠀
warn 9 broken links found on /cli-wrangler/configuration
warn  26:36   #keys
warn  70:25   #kv_namespaces
warn 102:49   /cli-wrangler/commands#secret
warn 134:71   /cli-wrangler/commands#kv
warn 142:31   /cli-wrangler/commands#generate
warn 142:96   /cli-wrangler/commands#init
warn 168:72   #ignoring-subsets-of-static-assets
warn 178:99   /cli-wrangler/install-update#update
warn 231:56   /cli-wrangler/webpack#using-with-workers-sites
⠀
warn 1 broken links found on /cli-wrangler/install-update
warn  22:77   #additional-installation-instructions
⠀
warn 1 broken links found on /cli-wrangler/webpack
warn  18:66   #backwards-compatibility
`

**Comment by adamschwartz** [comment]
I’m not entirely sure how to read this output. @ispivey can you possibly shed some light on how to tell if we’re good here?

**Comment by adamschwartz** [comment]
We shipped!
