### ISSUE TITLE
Update network map PoPs list

### ISSUE THREAD

**Issue by adamschwartz** [cloudflare/workers-docs-engine#87]
We should get an updated list of data center latitudes and longitudes for:

https://github.com/cloudflare/workers-docs-engine/blob/3d6cb82ec906d063e147497b8b3720923793cd7b/src/components/network-map.js#L6

Currently used on https://workers.cloudflaredocs.workers.dev/learning/how-workers-works

![image](https://user-images.githubusercontent.com/154613/88747962-e5548600-d11d-11ea-95c4-969a31f98b76.png)

**Comment by Electroid** [comment]
Is there a public facing Cloudflare API we can use to auto-update this data?

**Comment by adamschwartz** [comment]
Not that I know of. (I wish though!)
